#Creating building pipeline for dotnet app
stages:
  - stage: Continuos_integration
    displayName: continuos-integration
    jobs:
    - job: dotnet_Build
      displayName: dotnet-build-job
      steps: 
      - script: dotnet restore
        displayName: restore
      - script: dotnet build
        displayName: build
      - script: dotnet test
        displayName: test
      - script: dotnet publish
        displayName: publish artifacts
